services:
  - type: web
    name: telegram-order-bot
    env: go
    plan: free
    buildCommand: go build -o telegram-bot .
    startCommand: ./telegram-bot
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8409546502:AAHMu4vLc03J-pTXyzcbyvP9TikCVTorllc"
      - key: DISPATCHER_CHAT_ID
        value: "1155607428"
      - key: RENDER
        value: "true"
      - key: WEBHOOK_URL
        fromGroup: null
